apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: httpd-liveness
  labels: 
    app: httpd
spec:
  minReadySeconds: 3
  replicas: 3
  selector:
    matchLabels: 
      app: httpd 
  template:
    metadata:
      name: httpd
      labels: 
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort: 80
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 10
            httpGet:
              path: /
              port: 80
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 10
            httpGet:
              path: /
              port: 80
              
          