---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sri-hpa
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    kind: Deployment
    name: sri
  targetCPUUtilizationPercentage: 60