---
apiVersion: v1
kind: Service
metadata: 
  name: sri
spec:
  type: LoadBalancer
  selector:
    app: dashboardservice
  ports:
    - name: khaja
      port: 80
      targetPort: 9376
      protocol: TCP
