--- 
apiVersion: v1
kind: Service
metadata:
  name: service-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: nginx-svc
      port: 80
      targetPort: 80  
  selector:
    app: nginx
