---
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  selector:
    app: nginx
  type: ClusterIP   
  clusterIP: None
  ports:
    - name: nginx-svc
      port: 75
      protocol: TCP
      targetPort: 80  
      