apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-rs
  labels:
    app: httpd
spec:
  minReadySeconds:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
    template:
      metadata:
        name: httpd
        labels:
          app: httpd
    spec:
      containers:
        name: httpd
        image: httpd:2.4.57
        port:
          containerPort: 80
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 11
          timeoutSeconds: 1
          httpGet:
            path: /
            port: 80
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 11
          timeoutSeconds: 1
          httpGet:
            path: /
            port: 80
