---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  selector:
    app: jenkins
  type: ClusterIP
  ports:
    - protocol: TCP
      name: jenkins
      port: 8080
      targetPort: 8080  
  type: LoadBalancer     