---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
    - protocol: TCP
      name: nginx
      port: 80
      targetPort: 80  
  type: LoadBalancer     