pipeline{
     agent { lable 'dotnet7'}
     tools {
        maven 'mvn'
        dotnet 'donet7' 
}
    stages{
        stage('vcs')
            steps{
                git url:'https://github.com/CICDProjects/nopCommerceJuly23.git'
                    branch: 'develop'
        stage('build')
           steps{
            sh 'dotnet restore src/NopCommerce.sln'
                sh 'dotnet build -c Release src/NopCommerce.sln'
                sh 'dotnet publish -c Release src/Presentation/Nop.Web/Nop.Web.csproj -o publish'
                sh 'mkdir publish/bin publish/logs && zip -r nopCommerce.zip publish'
                archive '**/nopCommerce.zip'

           }            

            }
        }
    }