RS-Activity to create 5 pods with nginx and alpine in one pod::
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: postgres
  labels:
    app : nginx
spec:
  minReadySeconds: 4
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx   
      labels: 
        app: nginx
    spec:
      containers:
        - name: nginx
          image: postgres:16.0
          ports:
            - containerPort: 5432
        

----------------------------------------------------
Statefulset:
---
 apiVersion: apps/v1
 kind: StatefulSet
 metadata: 
   name: nginx
   labels: 
     app: nginx-ss
 spec:
   minReadySeconds: 4
   replicas: 4
   selector:
     matchLabels:
       app: nginx-ss
   template: 
     metadata:
       name: nginx
       labels:
         app: nginx-ss
     spec:
       containers: 
         - name: nginx
           image: nginx:latest
           ports:
             - containerPort: 80
           volumeMounts:
             - name: my-ss-volume   
               mountPath: /usr/share/nginx/html
   volumeClaimTemplates:
     - metadata:
         name: my-ss-volume
       spec:
         accessModes:
           - ReadOnlyMany  
         volumeName: my-ss-volume  
         storageClassName: managed
         resources:
            requests:
              storage: 10Gi
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ss
  labels:
    app: nginx-ss
spec:
  selector: 
    app: nginx-ss
  type: ClusterIP
  # ClusterIP: None
  clusterIP: None
  ports:
    - port: 80 
      protocol: TCP              

-----------------------------------------------
      

           

   


         
       
       
           


     






   
   

        

       
     



       



