---
apiVersion: v1
kind: Pod
metadata:
  name: init-container
spec:
  containers:
    - name: alpine
      image: alpine:latest
      args:
        - sleep
        - 5s
  initContainers:
    - name: nginx
      image: nginx:latest
      ports:
      - containerPort: 80
    
