apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: LoadBalancer
  ports:
  - name: tomcat
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: init-container
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  initContainers:
  - name: delay
    image: httpd
    ports:
    - containerPort: 80
    #- name: tomcat
    # image: tomcat:9.0.75-jdk8-corretto
    #ports:
# - containerPort: 8080    



